# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 657a36fa3b99759261b1616d6186895983dace9cebedb3d36be6504c364dc43c2cadba90e850b3512ea6566a9a6893f20186f7e68c60f000815e0bb877f1274c

test:
  secret_key_base: c2430c5914b7daf03b71ae856b22f5cb152ba3c0d4fa686bb87a72f2ebe17146d431faf27ac4e988e8b8872ccebb557b6dec882c742ae97b4b2dc417f28cf947

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
